Description =
[pf6]
[tab field]
"12319999
[field exit]
[field exit]
[field exit]
"*
[down]
"12384
[field exit]
"12384
[field exit]
[down]
[down]
[down]
[down]
[down]
[down]
[down]
[down]
[down]
[down]
[tab field]
[tab field]
"*ccata
[enter]
[enter]
[pf6]
[tab field]
"12319999
[field exit]
[field exit]
[field exit]
"*
[down]
"2490
[field exit]
"2490
[field exit]
[down]
[down]
[down]
[down]
[down]
[down]
[down]
[down]
[down]
[down]
[tab field]
[tab field]
"*ccata
[enter]
