Description =
"12
[enter]
"5
[enter]
[pf6]
"co1
[enter]
"1
[field exit]
[field exit]
"A
[enter]
[tab field]
[tab field]
"99999999t99
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[enter]
[tab field]
[tab field]
"99999999
[field exit]
"99
[tab field]
[tab field]
[tab field]
[tab field]
"y
[enter]
[wait inp inh]
[pf3]
[pf12]
