Description =
[wait app]
[wait inp inh]
"12
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0000 at (20,6)
wait 10 sec until cursor at (20,7)
[wait app]
[wait inp inh]
"5
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 002C at (7,2)
wait 844 msec 
[wait app]
[wait inp inh]
[pf6]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (17,44)
wait 10 sec until cursor at (17,45)
[wait app]
[wait inp inh]
"co1 month end
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
[field exit]
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[field exit]
[tab field]
[tab field]
[tab field]
[tab field]
[tab field]
"y
[field exit]
[field exit]
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 2453 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"2
[field exit]
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[field exit]
[field exit]
"99999999t
[tab field]
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[field exit]
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1812 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"3
[field exit]
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1250 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"4
[field exit]
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1187 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"5
[field exit]
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[field exit]
[field exit]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1032 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"6
[field exit]
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1219 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"12
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[field exit]
[field exit]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1234 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"13
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1188 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"14
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1406 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"15
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1234 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"16
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1203 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"17
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1906 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"52
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1704 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"60
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1250 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"61
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 2391 msec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"62
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1 sec 
[wait app]
[wait inp inh]
[pf12]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (4,23)
wait 10 sec until cursor at (4,24)
[wait app]
[wait inp inh]
"1
[field exit]
"80
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 10 sec until cursor at (7,29)
[wait app]
[wait inp inh]
[tab field]
[tab field]
"99999999
[enter]
[wait inp inh]
wait 10 sec until FieldAttribute 0008 at (7,28)
wait 1922 msec 
[wait app]
[wait inp inh]
[pf12]
