Description =
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"1
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"2
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"3
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"5
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"6
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"7
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"9
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"11
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"12
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"13
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"011
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"10
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"104
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"14
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"15
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"201
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"202
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"301
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"401
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"501
[field exit]
[enter]
[down]
[down]
[down]
"3431
[field exit]
[down]
[down]
"INT
[field exit]
[enter]
