USE [GartmanReport]
GO

/****** Object:  StoredProcedure [dbo].[spPolicyAdj]    Script Date: 05/09/2013 14:25:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[spPolicyAdj] 

 @BeginDate varchar(10) = '2011-10-01',
 @EndDate varchar(10) = '2011-10-31'

as

declare @sql as varchar(2500)

set @sql = '

select * from openquery(gsfl2k,''

SELECT SHLINE.SLINV# AS InvoiceNbr,
 SHLINE.SLDATE AS InvoiceDate,
 SHHEAD.SHIDAT,
 SHHEAD.SHODAT AS OrderDate,
 SHHEAD.SHOTYP,
 SHHEAD.SHVIAC,
 SHHEAD.SHCM,
 SHHEAD.SHPO#,
 SHLINE.SLCO AS Company,
 SHLINE.SLLOC AS Loc,
 SHLINE.SLORD# AS OrderNbr,
 SHLINE.SLSEQ#,
 SHHEAD.SHBIL# AS BillToCustNum,
 BillTo.CMNAME AS BillToName,
 BillTo.CMCO AS BillToCo,
 BillTo.CMLOC AS BillToLoc,
 Left(BillTo.CMADR3,23) AS BillToCity,
 Right(BillTo.CMADR3,2) AS BillToState,
 SHLINE.SLCUST AS ShipToCustNum,
 CUSTMAST.CMNAME AS ShipToCustName,
 CUSTMAST.CMADR3 AS ShipCustCitySt,
 SHLINE.SLBYP,
 SHLINE.SLITEM,
 SHLINE.SLSRL1,
 SHLINE.SLILOC,
 SHLINE.SLDESC,
 SHLINE.SLVEND AS VendorNum,
 VENDMAST.VMNAME AS VendorName,
 SHLINE.SLFCRG,
 SHLINE.SLPRCD,
 SHLINE.SLFMCD,
 SHLINE.SLCLS#,
 ITEMMAST.IMCLS#,
 SHLINE.SLDIV,
 SHLINE.SLQORD AS OrdQtyInvUM,
 SHLINE.SLQSHP AS ShipQtyInvUM,
 SHLINE.SLCUT,
 SHLINE.SLBLUS AS ShipQtyPriceUM,
 SHLINE.SLUM2 AS PriceUM,
 SHLINE.SLPRIC AS UnitPrice,
 SHLINE.SLPOR AS PriceOverride,
 SHLINE.SLPCRS,
 SHLINE.SLCOST AS UnitCost,
 SHLINE.SLEPRC AS ExtendedPrice,
 SLECST+SLESC1+SLESC2+SLESC3+SLESC4+SLESC5 AS ExtendedCost,
 SHLINE.SLSA,
 SHLINE.SLSLMN,
 CUSTMAST.CMSLMN,
 SHHEAD.SHSLSM,
 ITEMMAST.IMUMD4,
 SHLINE.SLPROMO#,
 SHHEAD.SHUSER,
 SHLINE.SLCOMC
 
FROM SHLINE 

Left JOIN CUSTMAST ON SHLINE.SLCUST = CUSTMAST.CMCUST 
Left JOIN SHHEAD ON (SHLINE.SLCO = SHHEAD.SHCO 
					AND SHLINE.SLLOC = SHHEAD.SHLOC 
					AND SHLINE.SLORD# = SHHEAD.SHORD# 
					AND SHLINE.SLREL# = SHHEAD.SHREL# 
					AND SHLINE.SLINV# = SHHEAD.SHINV#)
LEFT JOIN ITEMMAST ON SHLINE.SLITEM = ITEMMAST.IMITEM 
Left JOIN CUSTMAST BillTo ON SHHEAD.SHBIL# = BillTo.CMCUST 
Left JOIN VENDMAST ON SHLINE.SLVEND = VENDMAST.VMVEND
WHERE SHHEAD.SHIDAT >= ' + '''' + '''' + @BeginDate + '''' + '''' +
' And SHHEAD.SHIDAT <= ' + '''' + '''' + @EndDate + '''' + '''' +
' AND SHLINE.SLCLS# in (''''13035'''',''''13037'''')

ORDER BY SHLINE.SLINV#,
 SHHEAD.SHIDAT,
 SHLINE.SLCO,
 SHLINE.SLSEQ#,
 SHLINE.SLITEM
 '')
 '
 
 exec(@sql)
GO
