select * from openquery (gsfl2k,'

SELECT	GSFL2K.POLHIST.PLCO AS Company, 
		GSFL2K.POLHIST.PLLOC AS Location, 
		GSFL2K.POLHIST.PLPO# AS PONbr, 
		GSFL2K.POHHIST.PHVIACODE AS ShipViaCode, 
		GSFL2K.POHHIST.PHVIA AS ShipViaDesc, 
		GSFL2K.POLHIST.PLSEQ# AS POLineNbr, 
		GSFL2K.POLHIST.PLITEM AS ItemNbr, 
		GSFL2K.POLHIST.PLDESC AS ItemDesc, 
		GSFL2K.POLHIST.PLDIRS, 
		
		sum(GSFL2K.POLHIST.PLblur) AS QtyReceived, 
		sum(((IMWGHT*PLFACT)*PLblur)) AS TotalLineWeightRecd, 
		sum((((IMWGHT*PLFACT)*PLblur)*0.04)) AS TotalLineFreightEQ
		
FROM GSFL2K.POLHIST 
	LEFT JOIN GSFL2K.ITEMMAST ON GSFL2K.POLHIST.PLITEM = GSFL2K.ITEMMAST.IMITEM 
	INNER JOIN GSFL2K.POHHIST ON (GSFL2K.POLHIST.PLCO = GSFL2K.POHHIST.PHCO 
	AND GSFL2K.POLHIST.PLLOC = GSFL2K.POHHIST.PHLOC
	AND GSFL2K.POLHIST.PLPO# = GSFL2K.POHHIST.PHPO# 
	AND GSFL2K.POLHIST.PLREL# = GSFL2K.POHHIST.PHREL#)
	

where GSFL2K.POLHIST.PLITEM not in (''DAD15PT'',''DAD15QT'',''DAD151'')
AND (year(GSFL2K.POLHIST.PLRDAT)=year(current_date - 1 month)
			and month(GSFL2K.POLHIST.PLRDAT)=month(current_date)-1)
AND GSFL2K.POHHIST.PHRETURN <>  ''Y'' 
AND GSFL2K.POLHIST.PLVEND=13055 
AND GSFL2K.POLHIST.PLACTN= ''R''

group by GSFL2K.POLHIST.PLCO,
		GSFL2K.POLHIST.PLLOC,
		GSFL2K.POLHIST.PLPO#,
		GSFL2K.POHHIST.PHVIACODE,
		GSFL2K.POHHIST.PHVIA,
		GSFL2K.POLHIST.PLSEQ#,
		GSFL2K.POLHIST.PLITEM,
		GSFL2K.POLHIST.PLDESC,
		GSFL2K.POLHIST.PLDIRS 

order by plco,plloc,plpo#,plseq#
')
